# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

#    console_command.csv_import:
#        class: AppBundle\Command\CsvImportCommand
#        arguments:
#            - "@doctrine.orm.entity_manager"
#        tags:
#            - { name: console_command }
